name: CI/CD Ismênia

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a predefined GitHub Action
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run custom script on push
        run: ./script/custom_script.sh

  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a predefined GitHub Action
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run custom script on schedule
        run: ./script/custom_script.sh
